version: "3"

services:
  pgsql:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=developers
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    # volumes:
    #   - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-q", "-d", "hackaton", "-U", "sail"]
    #   retries: 3
    #   timeout: 5s
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
    networks:
      - sail
    depends_on: 
      - pgsql

networks:
  sail:
    driver: bridge
volumes:
    sailpgsql:
      driver: local
